"""add user role

Revision ID: 05495a3af760
Revises: dcdaf73596d6
Create Date: 2026-07-27 09:08:50.587635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05495a3af760"
down_revision: str | Sequence[str] | None = "dcdaf73596d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users", sa.Column("role", sa.String(), nullable=False, server_default="user")
    )

    op.alter_column("users", "role", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
