"""add refresh token to users

Revision ID: 384118e626ed
Revises: 05495a3af760
Create Date: 2026-07-28 08:34:47.975941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "384118e626ed"
down_revision: str | Sequence[str] | None = "05495a3af760"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("refresh_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
