"""add company query indexes

Revision ID: 4c6d522b941e
Revises: a37b0ac6f8af
Create Date: 2026-08-27 03:14:12.238772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6d522b941e'
down_revision: Union[str, Sequence[str], None] = 'a37b0ac6f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_index('ix_companies_owner_id_company_name', 'companies', ['owner_id', 'company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_owner_id_company_name', table_name='companies')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    # ### end Alembic commands ###
