"""add password reset fields

Revision ID: dcdaf73596d6
Revises: ca9e6da46917
Create Date: 2026-07-24 20:24:56.601541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcdaf73596d6"
down_revision: str | Sequence[str] | None = "ca9e6da46917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("reset_token", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("reset_token_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_token_expires")
    op.drop_column("users", "reset_token")
    # ### end Alembic commands ###
